version: "2"
linters:
  default: all
  disable:
    - depguard
    - wsl # deprecated
    - err113 # prefer wrapped errors
    - ireturn
    - varnamelen
    - noinlineerr
    - paralleltest
  settings:
    gosec:
      excludes:
        - G118

issues:
  uniq-by-line: false

severity:
  default: error
