name: Lint

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags: [ "v*" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.5.0
      - name: Format
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            gofmt -d .
            exit 1
          fi
