name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags: [ "v*" ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Lint
        uses: golangci/golangci-lint-action@v6
      - name: Test
        run: go test -timeout 2s -race ./...
      - name: Format
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            gofmt -d .
            exit 1
          fi
